import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const outDir = "dev-vault/.obsidian/plugins/campaign-map";

fs.mkdirSync(outDir, { recursive: true });
if (fs.existsSync("manifest.json")) {
  fs.copyFileSync("manifest.json", path.join(outDir, "manifest.json"));
}

function writeBundledStyles() {
  const maplibreCss = fs.readFileSync(
    "node_modules/maplibre-gl/dist/maplibre-gl.css",
    "utf8"
  );
  const ownCss = fs.existsSync("styles.css") ? fs.readFileSync("styles.css", "utf8") : "";
  fs.writeFileSync(path.join(outDir, "styles.css"), `${maplibreCss}\n${ownCss}`);
}
writeBundledStyles();

const ctx = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: path.join(outDir, "main.js"),
  minify: prod,
});

if (prod) {
  await ctx.rebuild();
  process.exit(0);
} else {
  await ctx.watch();
}
