import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const outDir = "dev-vault/.obsidian/plugins/campaign-map";

fs.mkdirSync(outDir, { recursive: true });
if (fs.existsSync("manifest.json")) {
  fs.copyFileSync("manifest.json", path.join(outDir, "manifest.json"));
}

function writeBundledStyles() {
  const maplibreCss = fs.readFileSync(
    "node_modules/maplibre-gl/dist/maplibre-gl.css",
    "utf8"
  );
  const ownCss = fs.existsSync("styles.css") ? fs.readFileSync("styles.css", "utf8") : "";
  fs.writeFileSync(path.join(outDir, "styles.css"), `${maplibreCss}\n${ownCss}`);
}
writeBundledStyles();

function copyDir(src, dest) {
  if (!fs.existsSync(src)) return;
  fs.mkdirSync(dest, { recursive: true });
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    const s = path.join(src, entry.name);
    const d = path.join(dest, entry.name);
    if (entry.isDirectory()) copyDir(s, d);
    else fs.copyFileSync(s, d);
  }
}
// Glyph PBFs (npm run fonts:build) and other runtime assets — not bundled by esbuild.
copyDir("assets/fonts/glyphs", path.join(outDir, "assets/fonts/glyphs"));

const ctx = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: path.join(outDir, "main.js"),
  minify: prod,
});

// Generation Web Worker (docs/02 §5): a fully separate bundle, since it runs
// in a real Worker context with no Node/Electron integration — no `external`
// list needed, src/gen/ has zero Obsidian/DOM imports by design.
const workerCtx = await esbuild.context({
  entryPoints: ["src/gen/worker/generationWorker.ts"],
  bundle: true,
  format: "iife",
  target: "es2020",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: path.join(outDir, "generation-worker.js"),
  minify: prod,
});

if (prod) {
  await ctx.rebuild();
  await workerCtx.rebuild();
  process.exit(0);
} else {
  await ctx.watch();
  await workerCtx.watch();
}
