/**
 * Replace-over-add advisory (Cradle learning 2026-07-15). A non-inverted landform
 * REPLACES the composed terrain toward its target inside its ring, so a
 * mountain/relief ADD-stamp beneath it is silently flattened — the trap that cost
 * the Cradle two iterations. This surfaces a NON-BLOCKING advisory: a one-line
 * Notice when such a landform is created / geometry- or param-edited, plus a
 * persistent hint line in its selection panel. Pure advisory — never blocks,
 * never alters bytes, never changes a single generated byte.
 *
 * Host-agnostic (no Obsidian import) so the gate drives it headlessly: the notice
 * fires through the injected `notify` seam (MapView passes the real `new Notice`).
 * The message string is the SAME one MapView shows in the panel and hands to the
 * Notice — build it once, here.
 */
import type { FabricFeature } from "../model/fabric";
import { landformReplaceOverlaps } from "../gen/fields/terrain";

/** The advisory MESSAGE for a landform, or `null` when it overlaps no add-stamp
 * (or isn't a qualifying non-inverted replace landform). The headless-testable
 * core — MapView renders this same string in the panel and passes it to `notify`.
 * Wording flagged for Jonah (see the task report). */
export function landformReplaceAdvisoryMessage(landform: FabricFeature, features: FabricFeature[]): string | null {
  const hits = landformReplaceOverlaps(landform, features);
  if (hits.length === 0) return null;
  const name = landform.properties.name?.trim() || "(unnamed)";
  const n = hits.length;
  return `landform '${name}' overlaps ${n} terrain stamp${n === 1 ? "" : "s"} — replace stamps flatten add-stamps inside them`;
}

/** Fire the advisory Notice IFF `landform` overlaps mountain/relief add-stamps.
 * Returns the message it fired (or `null` when silent) so a caller/test can
 * assert. `notify` is the host notice seam (MapView → `new Notice`). */
export function warnLandformReplaceOverlap(
  landform: FabricFeature,
  features: FabricFeature[],
  notify: (message: string) => void
): string | null {
  const message = landformReplaceAdvisoryMessage(landform, features);
  if (message) notify(message);
  return message;
}
